# Dependency Review Configuration for Shelly
# This file configures the GitHub dependency-review-action

# Vulnerability check settings
vulnerability-check: true
license-check: true

# License configuration
# Using allow-list approach (cannot use both allow and deny together)
allow-licenses:
  - MIT
  - Apache-2.0
  - ISC
  - BSD-2-Clause
  - BSD-3-Clause

# Severity configuration
fail-on-severity: moderate

# Additional settings
allow-ghsas: []
deny-packages: []
